# Generated by Django 4.2.1 on 2023-05-31 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('prenom', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('photos', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('descriptif', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True)),
                ('annee_sortie', models.IntegerField()),
                ('affiche', models.BinaryField(null=True)),
                ('realisateur', models.CharField(max_length=255)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmographie.categorie', to_field='nom')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=255, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('professionnel', 'Professionnel'), ('amateur', 'Amateur')], max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Film_Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmographie.acteur', to_field='nom')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmographie.film', to_field='titre')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('date', models.DateField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmographie.film', to_field='titre')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmographie.personne', to_field='pseudo')),
            ],
        ),
    ]
