# Generated by Django 4.2.1 on 2023-05-28 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmActeur',
            new_name='Film_Acteur',
        ),
    ]
