# Generated by Django 4.2.1 on 2023-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='descriptif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
