# Generated by Django 4.2.1 on 2023-06-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0002_alter_acteur_photos_alter_commentaire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='photos',
            field=models.ImageField(null=True, upload_to='filmographie/images/'),
        ),
    ]
