# Generated by Django 4.2.1 on 2023-05-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0003_alter_film_annee_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='annee_sortie',
            field=models.IntegerField(),
        ),
    ]
