# Generated by Django 4.2.1 on 2023-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0005_alter_acteur_age_alter_acteur_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='age',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
