# Generated by Django 4.2.1 on 2023-06-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0006_alter_acteur_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
