# Generated by Django 4.2.1 on 2023-06-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0007_alter_acteur_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
