# Generated by Django 4.2.1 on 2023-06-12 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0008_alter_acteur_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.date(2023, 6, 12)),
        ),
        migrations.AlterField(
            model_name='film',
            name='affiche',
            field=models.ImageField(blank=True, null=True, upload_to='filmographie/film/'),
        ),
    ]
