# Generated by Django 4.2.1 on 2023-06-13 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmographie', '0009_alter_acteur_nom_alter_commentaire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateField(default=datetime.date(2023, 6, 13)),
        ),
    ]
